# 使用 minimal-mistakes 主题
remote_theme: "mmistakes/minimal-mistakes@4.26.2"  # 使用最新的版本替换 4.26.2

# 添加插件
plugins:
  - jekyll-include-cache
  - jekyll-feed
  

# 其他必要的配置信息
title: "Your Site Title"           # 网站标题
description: "A brief description"  # 简短描述
baseurl: ""                         # 如果托管在 GitHub Pages，通常为空
url: "https://stru99ler.github.io"  # 网站 URL

# 主题的相关配置
author:
  name: "stru99ler"
  email: "dong.dsy0@gmail.com"

paginate: 5                    # 每页显示的文章数量
paginate_path: "/page:num/"    # 分页路径

defaults:
  - scope:
      path: ""                 # 空路径表示所有页面
      type: posts
    values:
      layout: single           # 文章页面布局
