title: "test-blog-title"
description: "test-blog-description"
baseurl: ""  # 根目录
url: "https://stru99ler.github.io"  # 替换为你的 GitHub Pages URL

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme  # 必须启用远程主题插件

remote_theme: "mmistakes/minimal-mistakes"  # 指定远程主题仓库

# 分页设置
paginate: 5  # 每页显示的文章数量
paginate_path: "/page:num/"

# 作者信息
author:
  name: "myname"
  avatar: "/assets/images/avatar.png"  # 上传头像到 assets/images 目录，并指定路径
  bio: "一句话介绍自己"

# 社交链接（可选）
# social:
#   email: "you@example.com"
#   github: yourusername
#   twitter: yourhandle
